### ISSUE TITLE
为什么都是空的

### ISSUE THREAD

**Issue by xjtushilei** [xiaoqiangcs/Python-For-MachineLearning#1]
师兄加油！

**Comment by xiaoqiangcs** [comment]
哈哈哈，最近忙科研，只实现了一个简单的knn,没好意思上传呢。欢迎follow我的GitHub

2017-05-08 23:39 GMT-07:00 xjtushilei <notifications@github.com>:

**Comment by xjtushilei** [comment]
Of course, I've paid attention to it.Let's follow each other
